### ISSUE TITLE
Dual Furnace Right Click Doesnt Work

### ISSUE THREAD

**Issue by ThatRandomGamer** [ThatRandomGamer/Mystic-Craft-Mod#4]
When the dual furnace is right clicked, it does nothing. The error log shows that it is missing a mapping.

Log- [16:29:39] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: class com.TRGamer28.coppermod.blocks.DualFurnace.TileEntityDualFurnace is missing a mapping! This is a bug!
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:796) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: class com.TRGamer28.coppermod.blocks.DualFurnace.TileEntityDualFurnace is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.writeInternal(TileEntity.java:89) ~[TileEntity.class:?]
	at net.minecraft.tileentity.TileEntity.writeToNBT(TileEntity.java:80) ~[TileEntity.class:?]
	at com.TRGamer28.coppermod.blocks.DualFurnace.TileEntityDualFurnace.writeToNBT(TileEntityDualFurnace.java:130) ~[TileEntityDualFurnace.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.getTileNBT(BlockSnapshot.java:132) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:61) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:82) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:113) ~[BlockSnapshot.class:?]
	at net.minecraft.world.World.setBlockState(World.java:393) ~[World.class:?]
	at com.TRGamer28.coppermod.blocks.DualFurnace.BlockDualFurnace.onBlockAdded(BlockDualFurnace.java:81) ~[BlockDualFurnace.class:?]
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:662) ~[Chunk.class:?]
	at net.minecraft.world.World.setBlockState(World.java:400) ~[World.class:?]
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:199) ~[ItemBlock.class:?]
	at net.minecraft.item.ItemBlock.onItemUse(ItemBlock.java:57) ~[ItemBlock.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:860) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:200) ~[ItemStack.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:504) ~[PlayerInteractionManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:767) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(CPacketPlayerTryUseItemOnBlock.java:68) ~[CPacketPlayerTryUseItemOnBlock.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(CPacketPlayerTryUseItemOnBlock.java:13) ~[CPacketPlayerTryUseItemOnBlock.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
	... 5 more
[16:29:41] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: class com.TRGamer28.coppermod.blocks.DualFurnace.TileEntityDualFurnace is missing a mapping! This is a bug!
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:796) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: class com.TRGamer28.coppermod.blocks.DualFurnace.TileEntityDualFurnace is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.writeInternal(TileEntity.java:89) ~[TileEntity.class:?]
	at net.minecraft.tileentity.TileEntity.writeToNBT(TileEntity.java:80) ~[TileEntity.class:?]
	at com.TRGamer28.coppermod.blocks.DualFurnace.TileEntityDualFurnace.writeToNBT(TileEntityDualFurnace.java:130) ~[TileEntityDualFurnace.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.getTileNBT(BlockSnapshot.java:132) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:61) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:82) ~[BlockSnapshot.class:?]
	at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:113) ~[BlockSnapshot.class:?]
	at net.minecraft.world.World.setBlockState(World.java:393) ~[World.class:?]
	at net.minecraft.block.Block.removedByPlayer(Block.java:1422) ~[Block.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:294) ~[PlayerInteractionManager.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:288) ~[PlayerInteractionManager.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.tryHarvestBlock(PlayerInteractionManager.java:335) ~[PlayerInteractionManager.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.onBlockClicked(PlayerInteractionManager.java:171) ~[PlayerInteractionManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayerDigging(NetHandlerPlayServer.java:719) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(CPacketPlayerDigging.java:56) ~[CPacketPlayerDigging.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.processPacket(CPacketPlayerDigging.java:12) ~[CPacketPlayerDigging.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
	... 5 more

**Comment by Calculus-Master** [comment]
I made a change to RegistryHandler; the Tile Entities were not being registered:
[](https://github.com/ThatRandomGamer/Mystic-Craft-Mod/blob/master/src/main/java/com/TRGamer28/coppermod/util/handlers/RegistryHandler.java)
